### ISSUE TITLE
Support for ruby kernel

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-ruby#1]
Is `ruby` going to be the next supported kernel? I can help with that!  😄

**Comment by BoPeng** [comment]
Another student is joining the group. He has some experience with ruby so this is something for him to get familiar with sos. I suppose you can help test it. Actually, if your group is using SAS 9.4, I need help in testing the sos-sas module because I only have SAS 9.3 around.

**Comment by HenryLeongStat** [comment]
Yes, they are using SAS 9.4. However, all the desktops here are using `Windows 7` except for one of my desktops using `Ubuntu`. I can try to test it on `Windows 7` or apply for a SAS 9.4 license to install on my `mac` or the desktop using `Ubuntu`.

**Comment by HenryLeongStat** [comment]
Move to [here](https://github.com/vatlab/sos-sas/issues/1).

**Comment by BoPeng** [comment]
@HenryLeongStat Well, the `sos-ruby` project is created but the prior arrangement is canceled so you now get a chance to learn ruby if you are interested...

I have set up the basic information so you should be able to see the Ruby language listed if you have the ruby kernel installed. I can see ruby has pretty good support for JSON format so I think we should be able to use JSON to handle most data types. This sounds lazy because we could handle basic types more efficiently but let us first get things working before we optimize them.

**Comment by HenryLeongStat** [comment]
OK! I will handle it. 

Should I take a look with the tutorial of JSON (or JS) first? Actually, I am working on a web crawler project and thinking this is a very good opportunity to learn JS and elements of website (might be helpful later for the migration of VT from sourceforge to git) , since I learnt html for a year in high school.

**Comment by BoPeng** [comment]
Sure. JSON is pretty simple (and useful) to learn.

For web crawler, spend half a day to google first because there are more than dozens of web crawlers out there and there is no need to write your own. Of course you need to lean JS and elements of website to UNDERSTAND and USE them.

**Comment by HenryLeongStat** [comment]
Understood! Will do! I am reading a book about web crawler (only 200 pages). Let me take a look with JSON during the weekend! 😄

**Comment by HenryLeongStat** [comment]
Started working on that!

The followings are the mapping of datatype between `Ruby` and `SoS`:

`Ruby`     |        `SoS`
 --- | --- 
 numeric |             numeric 
string    |             string
Ruby Array    |    list
Ruby Hash     |   dict
Ruby Ranges  |  python range????
Booleans  |  Booleans
Matrix | np.matrix
Daru::DataFrame | pd. DataFrames
array|np.ndarray


Reference: 
1. https://www.tutorialspoint.com/ruby/ruby_variables.htm
2. https://blog.botreetechnologies.com/ruby-basic-data-types-12d63251e33c

**Comment by HenryLeongStat** [comment]
Seems Ruby supports `feather` as well!!!!

Ref: https://www.slideshare.net/kou/datasciencerb

**Comment by HenryLeongStat** [comment]
I actually find that syntax and data type in `Ruby` is quite similar to `julia`!

**Comment by HenryLeongStat** [comment]
`python` `Named array` will be converted to `Ruby` `Hash`

**Comment by HenryLeongStat** [comment]
More or less, the kernel is done and the test is added! :)

Going to update the documentation.

**Comment by BoPeng** [comment]
The test fails with

```
0.61s$ sudo apt install libzmq3-dev libzmq-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libzmq3-dev : Conflicts: libzmq-dev
E: Unable to correct problems, you have held broken packages.
```
so it is a linux issue. It is better to find a linux machine to figure out the correct command to install iruby.

**Comment by HenryLeongStat** [comment]
I can take a look at it using my ubuntu machine.

Professor, could you take a look at [this testing script](https://github.com/vatlab/sos-ruby/blob/master/test/test_Ruby_kernel.py)? Some variables like `null_var`, `mat_var`, `char_var`, work fine in jupyter notebook, but somehow the test keeps failing...
