### ISSUE TITLE
Change shown name from `ruby` to `Ruby`

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-ruby#2]
@BoPeng Professor, when I tried sth like:

```
SoS:
a=1

ruby:
%get a
```
An error message shows up: 
Magic %get failed because the language module for ruby is not properly installed. Please install it according to language specific instructions on the Running SoS section of the SoS homepage and restart Jupyter server.

Also, `Ruby` shows as `ruby` in `SoS notebook`. How can I fix it?

**Comment by BoPeng** [comment]
The kernel name `ruby` will be displayed if the language module is not properly installed. Let me see.

**Comment by HenryLeongStat** [comment]
But I am still able to use Ruby in SOS notebook. 
<img width="925" alt="screen shot 2018-06-27 at 5 33 48 pm" src="https://user-images.githubusercontent.com/26916551/42003277-45376214-7a30-11e8-9b04-2ea0b58ba84a.png">

**Comment by BoPeng** [comment]
Yes, any kernel is usable in SoS. The difference is that without language module `%get` does not work.

**Comment by HenryLeongStat** [comment]
fix by https://github.com/vatlab/sos-ruby/commit/7ff945f94687ba20086a2ada0dc0119395f9ad23
