### ISSUE TITLE
Failed to pass dataframe under linux

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-ruby#8]
![image](https://user-images.githubusercontent.com/9889312/42971874-46cb5370-8b73-11e8-8471-b182eb6551a7.png)

![image](https://user-images.githubusercontent.com/9889312/42971952-80d4e536-8b73-11e8-88a8-ab91f20d101b.png)

**Comment by HenryLeongStat** [comment]
You have to install `daru` and `nmatrix` first.

`$ gem install daru`
`$ gem install nmatrix`

I am working on the documentation and will include them there.

**Comment by BoPeng** [comment]
Thanks. I will update `.travis.yml` for this.
I have also updated features page, and you will have to update installation instruction.

**Comment by HenryLeongStat** [comment]
Will do!!  😄

**Comment by HenryLeongStat** [comment]
Btw, Professor, you can install `iruby` on linux machine? I failed to do so on my ubuntu machine this morning...

**Comment by BoPeng** [comment]
Ok. They pass, but

![image](https://user-images.githubusercontent.com/9889312/42973327-6a2eeffc-8b78-11e8-8fc5-6ded27d05227.png)

**Comment by BoPeng** [comment]
Check your linux version, you will have to compile czmq from source according to iruby instruction if you are using 14.4, not version 17 of Ubuntu.

**Comment by HenryLeongStat** [comment]
It works fine on my end...?
<img width="928" alt="screen shot 2018-07-19 at 5 27 07 pm" src="https://user-images.githubusercontent.com/26916551/42973514-fb243a94-8b78-11e8-889c-3102a9b4a487.png">

**Comment by BoPeng** [comment]
Test on a linux machine then...

If you want complete control over a linux machine, install vmware player or virtualbox and download existing vms from https://www.osboxes.org/vmware-images/.

**Comment by HenryLeongStat** [comment]
That's weird, all the `int` fail on your end... What `Ruby` and `iruby` versions are installed on your machine? Mine are 2.5.1
<img width="254" alt="screen shot 2018-07-19 at 5 30 20 pm" src="https://user-images.githubusercontent.com/26916551/42973624-744dbb70-8b79-11e8-965b-6b8d96ae06ed.png">

**Comment by BoPeng** [comment]
I am 2.3.1

![image](https://user-images.githubusercontent.com/9889312/42973689-ba75d9fc-8b79-11e8-9a36-b0bc4a97c662.png)

**Comment by HenryLeongStat** [comment]
>Check your linux version, you will have to compile czmq from source according to iruby instruction if you are using 14.4, not version 17 of Ubuntu.

I guess I need to compile it from source.
```
ml69@henry:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
```

**Comment by BoPeng** [comment]
Changing all `instance_of` to `is_a` fixes the problem.... does it make sense to do it? 

https://stackoverflow.com/questions/3893278/ruby-kind-of-vs-instance-of-vs-is-a

**Comment by BoPeng** [comment]
Ruby test passes on travis!

https://travis-ci.org/vatlab/sos-ruby

**Comment by HenryLeongStat** [comment]
>Changing all instance_of to is_a fixes the problem.... does it make sense to do it?
https://stackoverflow.com/questions/3893278/ruby-kind-of-vs-instance-of-vs-is-a

Let me try... I used `is_a?` before, but I remember I chose `instance_of?` instead of `is_a?` because `is_a?` failed me couple times.

>Ruby test passes on travis!
https://travis-ci.org/vatlab/sos-ruby

Awesome!!! 🥂

**Comment by HenryLeongStat** [comment]
If only `Integer` fails, how about we just use `is_a?` for `integer`?

**Comment by BoPeng** [comment]
`instance_of` is very strict and does not accept subclasses, `is_a` is better but it is easier to get  related objects with different types to both return true, thus the order of `is_a` is important (test less general case first).

**Comment by HenryLeongStat** [comment]
I see your point. People seem to like define their own objects which might be subclasses of the general parent classes. Maybe it is better to use `is_a?` instead... Let me try on my end!

**Comment by BoPeng** [comment]
I changed `instance_of` to `is_a` because otherwise the tests would be pass on my linux box. This could be due to ruby version but supporting an older version does not hurt.

I have just released `sos-ruby` 0.9.15.0, which is our first public release. Please keep working on the documentation etc and we will release 0.9.15.1 etc when we encounter any bug.

**Comment by HenryLeongStat** [comment]
OK! I think `is_a` works! 
<img width="328" alt="screen shot 2018-07-19 at 5 52 53 pm" src="https://user-images.githubusercontent.com/26916551/42974386-9977b830-8b7c-11e8-8169-539edf89c717.png">
<img width="212" alt="screen shot 2018-07-19 at 5 52 58 pm" src="https://user-images.githubusercontent.com/26916551/42974392-9be92c2a-8b7c-11e8-88f9-e619ebc9ba1e.png">
<img width="871" alt="screen shot 2018-07-19 at 5 53 02 pm" src="https://user-images.githubusercontent.com/26916551/42974394-9dede7e0-8b7c-11e8-9a07-3c1655c0d955.png">

**Comment by BoPeng** [comment]
Congratulations on the first release of `sos-ruby` and many thanks for your great work!

**Comment by HenryLeongStat** [comment]
I always learnt A LOT from you, Professor!! And enjoy working with you so much! 😄 

Are there any other tasks that I can help?
